import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Robe d'été fleurie",
    description:
      "Robe légère à motifs floraux, parfaite pour les journées ensoleillées. Tissu respirant et coupe flatteuse.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=300&text=Robe+fleurie",
    category: "dresses",
    tags: ["été", "floral", "casual"],
  },
  {
    id: "2",
    name: "Veste en jean oversize",
    description:
      "Veste en jean au style décontracté avec coupe oversize tendance. Parfaite pour compléter n'importe quelle tenue.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=300&text=Veste+jean",
    category: "outerwear",
    tags: ["denim", "casual", "automne"],
  },
  {
    id: "3",
    name: "Sac à main en cuir",
    description: "Sac à main élégant en cuir véritable avec finitions soignées et compartiments pratiques.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=300&text=Sac+cuir",
    category: "accessories",
    tags: ["cuir", "élégant", "pratique"],
  },
  {
    id: "4",
    name: "Sneakers minimalistes",
    description: "Baskets au design épuré et minimaliste, confortables pour un usage quotidien.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=300&text=Sneakers",
    category: "shoes",
    tags: ["casual", "confort", "minimaliste"],
  },
  {
    id: "5",
    name: "Canapé scandinave",
    description: "Canapé 3 places au design scandinave avec pieds en bois clair et tissu durable.",
    price: 599.99,
    image: "/placeholder.svg?height=400&width=300&text=Canapé",
    category: "furniture",
    tags: ["salon", "scandinave", "confort"],
  },
  {
    id: "6",
    name: "Lampe de bureau articulée",
    description: "Lampe de bureau moderne avec bras articulé, idéale pour l'espace de travail.",
    price: 59.99,
    image: "/placeholder.svg?height=400&width=300&text=Lampe",
    category: "furniture",
    tags: ["éclairage", "bureau", "design"],
  },
  {
    id: "7",
    name: "Robe de soirée noire",
    description: "Élégante robe noire pour les occasions spéciales, avec coupe ajustée et détails raffinés.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=300&text=Robe+noire",
    category: "dresses",
    tags: ["élégant", "soirée", "noir"],
  },
  {
    id: "8",
    name: "Chemise en lin",
    description: "Chemise décontractée en lin naturel, parfaite pour les journées chaudes.",
    price: 45.99,
    image: "/placeholder.svg?height=400&width=300&text=Chemise+lin",
    category: "clothing",
    tags: ["lin", "été", "casual"],
  },
  {
    id: "9",
    name: "Table basse en marbre",
    description: "Table basse élégante avec plateau en marbre et pieds en métal doré.",
    price: 249.99,
    image: "/placeholder.svg?height=400&width=300&text=Table+marbre",
    category: "furniture",
    tags: ["salon", "marbre", "luxe"],
  },
  {
    id: "10",
    name: "Boucles d'oreilles géométriques",
    description: "Boucles d'oreilles au design géométrique moderne, légères et élégantes.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=300&text=Boucles",
    category: "accessories",
    tags: ["bijoux", "géométrique", "tendance"],
  },
  {
    id: "11",
    name: "Pantalon taille haute",
    description: "Pantalon élégant à taille haute avec coupe droite, parfait pour le bureau ou les sorties.",
    price: 69.99,
    image: "/placeholder.svg?height=400&width=300&text=Pantalon",
    category: "clothing",
    tags: ["élégant", "bureau", "taille haute"],
  },
  {
    id: "12",
    name: "Fauteuil en velours",
    description: "Fauteuil confortable en velours avec accoudoirs et pieds en bois foncé.",
    price: 349.99,
    image: "/placeholder.svg?height=400&width=300&text=Fauteuil",
    category: "furniture",
    tags: ["salon", "velours", "confort"],
  },
  {
    id: "13",
    name: "Collier minimaliste",
    description: "Collier fin avec pendentif géométrique, parfait pour un look élégant au quotidien.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=300&text=Collier",
    category: "accessories",
    tags: ["bijoux", "minimaliste", "quotidien"],
  },
  {
    id: "14",
    name: "Robe longue bohème",
    description: "Robe longue au style bohème avec imprimés ethniques et coupe fluide.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=300&text=Robe+bohème",
    category: "dresses",
    tags: ["bohème", "été", "imprimé"],
  },
  {
    id: "15",
    name: "Étagère murale",
    description: "Étagère murale en bois et métal au design industriel, parfaite pour exposer vos objets décoratifs.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=300&text=Étagère",
    category: "furniture",
    tags: ["rangement", "industriel", "décoration"],
  },
]
